# This workflows will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: Upload Python Package

on:
  push:
    branches:
      - master

jobs:
  test:
    name: Release
    runs-on: ubuntu-latest
    steps:
    - run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
    - run: echo "${{ env.date }}"
